version: '2'
services:
  front:
    build: ./front
    ports:
    - "8080:8080"
    volumes:
    - ./front:/home/app/front
  greeting:
    build: ./greeting
    volumes:
    - ./greeting:/home/app/greeting
